# create models from ASVset genome objects

In [1]:
from load_genomes_to_modelseedpy import GenomeLoader
from cobra.io import write_sbml_model
# from glob import glob
from tqdm import tqdm
import os

loader = GenomeLoader()
# genome_ids = loader.list_available_genomes()#[:10]

def write_model(gID):
    model = loader.build_model(gID, printing=False)
    write_sbml_model(model, f'models/{gID}.xml')

# for genome_id in tqdm(genome_ids):
#     model_path = f'models/{genome_id}.xml'
#     if os.path.exists(model_path):  continue
#     try:
#         model = loader.build_model(genome_id, printing=False)
#         write_sbml_model(model, model_path)
#         # print(f"✓ {genome_id}") 
#     except Exception as e:
#         print(f"✗ {genome_id}: {e}")


# parallelize the effort
args = [gID for gID in loader.list_available_genomes() if not os.path.exists(f'models/{gID}.xml')]#[:2]
print(len(args), "will be processed")
parallelize = False
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = int(cpu_count()/8)
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(write_model, args)
    
    print(f"missing iterativeIDs", missing_iterativeIDs)
    print(f"missing IDs", missing_IDs)
else:
    for arg in args:
        # print(arg)
        write_model(arg)

100%|██████████| 1698/1698 [1:21:00<00:00,  2.86s/it]

# create community models from the member models and abundances

In [1]:
from cobra.io import read_sbml_model, write_sbml_model
from pandas import read_csv, Series
from mscommunity import build_from_species_models
from tqdm import tqdm
from json import load
import os

iterativeIDs = load(open("model_inputs/iterativeIDs.json", 'r'))
ASV_sets = load(open("modeling_files/ASV_sets.json", 'r'))
redunant_asvs = {v:k for k,vs in ASV_sets.items() for v in vs}
abundances = load(open("modeling_files/ASVset_abundances.json", 'r'))

def create_comm(item):
    sample, abundances = item
    models = []
    for ASV, abun in abundances.items():
        ASVset = iterativeIDs[redunant_asvs.get(ASV, ASV)]
        model_path = f"models/{ASVset}.xml"
        #TODO:  investigate why these ASVs did not have any genomeIDs
        if not os.path.exists(model_path):  # some ASVs have no genomeIDs
            continue
            
        model = read_sbml_model(model_path)
        model.id = ASVset
        models.append(model)
    modelID = f"{sample}_comm"
    modelName = f"{sample}_comm"
    comm_model = build_from_species_models(models, modelID, modelName, abundances, printing=True)
    write_sbml_model(comm_model, f"models/{modelID}.xml")

# parallelize the effort
args = [item for item in abundances.items() if not os.path.exists(f"models/{item[0]}_comm.xml")]
print(len(args), "will be processed")
parallelize = False
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = min(len(args), int(cpu_count()/8))
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(create_comm, args)
    
    print(f"missing iterativeIDs", missing_iterativeIDs)
    print(f"missing IDs", missing_IDs)
else:
    for arg in args:
        # print(arg)
        create_comm(arg)
        break

modelseedpy 0.3.3
19 will be processed
('10AB', {'9f86297104372f6378c6bf3dc1a8e8ec': 0.0035438998239284624, 'acb819d2b09f090ba6c3112028bbc54b': 0.009290477841294643, '1f1ff56fd37c5c9b1a9ac7b1d99e10b0': 0.004095232026216364, '496ed1835247fa310353bd53160fad4a': 0.00837070728222818, '18ec5da6c765ede0c426af393f8ce656': 0.001916409554369221, '34bc76cd76ea83cf74430a3bbb56ac82': 0.002716901515492011, '2da3ff46bfa58a914368731cfd699785': 0.0028918434538044934, '44f513ba8d222b088ba2ad6e7ab85b8c': 0.0013915836993949819, '09304de7bcdde93714df6d4800a79b4d': 0.004932832887591158, '6dfb10e6d92b2c7ec87175ad560bed2e': 0.009733133988568015, '495cc889a2e82868482b1feb2f71fbd0': 0.0033371502468193498, 'f8ec439cb9f26e97be2793df3c52b03d': 0.002038338798054379, '5ec4e02584b8c58b33bde92395188ffa': 0.0026612381651140034, 'de794e5f913a822d437c41f82c49a80e': 0.0013544747991429775, 'df94cb7c1f51d6e7df4a969d561b0a4d': 0.012529554566019408, '0138936a169c4a0914606cedbcd38fa6': 0.005115726743109697, '22958f01426d8f1fe3f4922e13710669': 0.0037135405007855705, '9cef27fb5c42d04a7e949300061958c1': 0.002563164643019421, '38b371de3be6ddef03bea94294e9830d': 0.11770412527324882, '63f37ee4b481fccdffca10160ed5b944': 0.002390873330430026, '19463e5fe824700110e4a4ec8afe0512': 0.001532067383196944, 'c39f594d9d2493b66260c1f7503e5ea1': 0.007742506643703982, '7ba3402ab86ac791941e0dc862234ee8': 0.001980024811944086, 'a5b2537343a26f4daf0379a8b46eb2ef': 0.001630140905291527, 'e29f9ab1342fe7d53d4f1e2d03bb5969': 0.0017176118844569662, '04869be25e3dc4d526ce3824d407aedf': 0.0024624404851925513, 'ef9fddde19882aba901f1b0419ec09d8': 0.0010629048886099091, '3343d19c0bc1759a66023cbc86c92592': 0.014085477670806926, '3ade0fa13e56aac194bb3373200d6def': 0.0022874985368708705, 'd48429274cd09a4257ad8b24c009e8fd': 0.023707284968628124, '051d14c7d7e9a5358e8da8a52b48bca3': 0.0022848479011385843, 'e1809c067af83a3dc4623ce28f35fe79': 0.0023935239661623123, '5976a56adfe903f7348b5eb5689e3c55': 0.0013491735276784053, 'ea156f972cd3802c3fac147e4200ba7a': 0.0032046184602050475, 'b65ddb808f41ed58f0a87829f790124c': 0.005364886491935387, 'd5e86e0fe7c13c5751606c96f3788345': 0.003042929700553995, 'e6485d233ed2b8b9a2f3f50f0747b9d2': 0.0015108623073478533, '499a635c6e7dcd5c8ef518302aa50011': 0.001131821407640148, '021d1583edfe105a9c99264ea9f3d2d6': 0.0014366445068438444, '93fadef301b62aa732e42bf1142b3afa': 0.002849433292097115, 'f0f5fe3a3ccc66ce7e67e82294654107': 0.002314004894193731, 'da47a34fd036b068ca0c5eaf185e2082': 0.0028600358350262586, '76ef356d895e6434580f18ab74a63e6c': 0.0043019816133346754, 'eca00dcc9a01255b6cb66fbd5b3bd285': 0.0014286925996469862, '3d34374d81a96ce4972b93ef5dae9b82': 0.00562464878369022, 'dcc552ee0bfe584a9f79fd3d7893047f': 0.02082339342202049, '3487ee381e9bba57861b67ac3936d665': 0.009876268318111461, 'e1d678e0c2f5463421eec27874b0fab3': 0.0010788086929944274, 'b61513eef1a69690c5d43ca0cb8f5c1b': 0.0016248396338269552, 'e8c1e783e60161fe039cc419a3717b1f': 0.001550621833322946, '535887d75db6f21831a65b42a9d5752f': 0.0010125428096964743, 'fff6f2b1de224120c999dde9f25fcd0a': 0.0012060392081441572, '492422c8881f2e782fccb0225f1c68ab': 0.0094124070849798, '482bb3761a6b11b4cfb4e1b618231157': 0.002162918667462625, '08ea1c9b9d368cd6d9bfeb8857e90315': 0.013043777878064503, 'cd05a4b1cda569ae366c6980823f4c72': 0.026821781813935446, 'a6efdb52a04e05a2a1be52f5516784fa': 0.0031542563913008106, '2e707ae206fd30644537a8329e2b9476': 0.004036918050115269, 'bb617d32673d5f60d6216a07ad7a42bc': 0.002306052986996873, 'e1382120e151d51cb3b3b6900845f1c8': 0.014522832556624924, '4ced6b735a53af484d0cf4f620846dcd': 0.0071779212527454525, '197c1736a92b42d2671a7ea927a9d7d8': 0.0024332835021466026, '9335b7a207b486ae9975e735cd30a814': 0.0013862824279304098, '26ef86afa44dbbdebbae8f35e590f52e': 0.00168845489140182, '48ca5b4f7cb58d4a146837de341a2604': 0.0023829214132239703, 'a67c7071b283c3513d9aa4cf63879d6e': 0.0017308650631183966, '164212c0910ca9770a6bd13bcb2c5d05': 0.0014605002284344187, 'd96a2ea1b09f080f66ce79b9ddfa768e': 0.007355513836799419, '9026ee9ce58d36be3646689861848080': 0.0019058070114400772, 'ab2050607cb3fe172ea918d5a17a46c7': 0.005677661498335941, '28b5f35cfb5f0516e5e5f896428abdcd': 0.003599563174306469, '344b8fcfc08a17bb7443c1ad11ea3151': 0.0014233913281824142, '36e38981bc99d5d7fdd5959ca41f6313': 0.0011397733148370062, '52708c2cfa926ba9b2f69878c97cee2c': 0.017724800381097687, '50285c59a58cda2d889cb954c022a93a': 0.002306052986996873, 'd5004573c96ec6eedcc4348d1145db37': 0.0010841099644589996, 'bc15f0e20879b79188fa5ea9e191428c': 0.002613526711923657, 'ad922999ec6a8228be4358e848e86bc2': 0.0010178440811610464, 'c99bcc4ed3b2887c914e9faf48d63e3f': 0.001394234335127268, '405648482a348320fe4470fddebb64c6': 0.0026161773576651413, 'caafd6d1ef718ac1a2b7473f47d9340b': 0.0012404974726638756, 'e94618b44f9856c9a2151cab1800a460': 0.0024438860450757467, '0b291123c105140e6524bb2a3cf8e278': 0.0014154394209855562, 'c99dd2353697161faecee673e0eda7b2': 0.0013915836993949819, '9e54e8d50785a84f97b38e3eb665dda0': 0.0020913515026909015, 'a19152d55f42fc72a3a0f985d2615aab': 0.0025048506569091277, '664e1ee046659d47ded4a40ad1133a33': 0.0015055610358832813, '8855fec4062970bb235780d6469a1d6d': 0.0010231453526256184, '669b72740b8bed1bcedbdbaa4b8be1e7': 0.0029793144329699327, '5db694edf839eff28cb6a47bb5b50693': 0.0013544747991429773, '8fa90e60ddaccabffcd68f6a481318a2': 0.0014048368880656098, '1d4b9f3ddf33afdf5308213897846090': 0.006655746033503499, 'c668608bc7be0382064b57d5505c7e23': 0.0028441320206325426, '894d5f2608f2a0e9e3bf2499f1cc6130': 0.007262741586169409, '66575db7635d648549a9eb5a4eafb710': 0.0030853398622613746, '9c90a0c962c8b6283f7a71b644fce90c': 0.0025446101928934184, '613cd0ab8ed46a361940e06efaecdb6d': 0.003408717401581875, '201a9f507c9b354eb162adf1f311c607': 0.0031940159272851017, '19cfc988be2bc698e4e8e24f3c017dad': 0.0017865284034872056, '2c4fdd0845cdde26dc7d98f576bb10e7': 0.0010284466240901905, '0b736ddea36ed16291fa058fe28061f8': 0.0245104275754924, '7c4029c77a50ad0582c758eabe8c1410': 0.007930701770687094, '49c907377454c6980ff0a520fe40abe2': 0.004299330997620784, '95d0db82a69ee10f3b5ed0f06ba96949': 0.0015718269191812345, 'aa15b94e77f3955a73a15e15187b6482': 0.001463150854157507, '07e00e1bcc9d9a3c50591f721785e591': 0.04699046824010888, '1d837cc6d80881adecbb106f01c1b042': 0.00606200365949902, '6075255b58efbd350ad34112f80f970a': 0.0093938526348538, 'b7bc2902499297dc5de20e8748a42d33': 0.006125618917073885, 'e21f14506da976def600538a8f860f0b': 0.0021152072142722783, '4bcf2ed3c27ef7222d2bf177640edef4': 0.0032682337177799125, '29d5a1f45c97760080e874715394bcfe': 0.001606285183700953, 'a8c0192a45a12e2f86fe50245c36917d': 0.001121218864711004, 'aa9c5ae2ec6da55f30edd92e3de37eff': 0.0019826754376671744, 'b24d3443426aac9dca3451d65ba14d55': 0.001969422269014942, '89d1d4064aa11fd1f3efb8e1345c813f': 0.0020171337021868928, 'da28c80a7a1b2838789eb2ad598db9a0': 0.001317365898890973, '01b5383db868117f04bfd197603f736b': 0.0019137589186369354, 'cb08126894ac0c8eeddc7b86d1ab1eb9': 0.012195574483769765, 'e95282c3197d4315d84f31d177642c58': 0.0010390491670193348, 'c05932b0e9b0bcf5f076c8971c6bab60': 0.012237984645477139, '868a2dd217365ddd6d6ab64d48aeed4a': 0.001076158067271339, '8c740d5ca21893b47c7619df1247c75d': 0.0010337478955547625, '05771e0f1c5425fc486934e2beb87956': 0.006828037346092894, '37a9f9625f201b6e61c29ac09ec54683': 0.00479765046524457, '24b5476371dc34ef4f12b359d6ea6fe4': 0.0013624267063398355, 'b73b1ef694c71eec29bf86c697f26b20': 0.0012935101773003986, '687530ef97a8574b08b65e6100ed1f16': 0.0012298949297347315, '70775be7835f6d6a6ecb0d7039b355e3': 0.0013067633559618289, 'eaa1d57a577a4aa93aceab1782827ea8': 0.0012457987441284477, '8a1c973b6094cbd560f363581ce1beba': 0.0012908595415681125, '07bb3ab197992af0b741d1b71fc16c74': 0.0011344720433724342, '4c7b0d554a1103b7872deded4bccb4ea': 0.0012325455654670174, '3bb8c91a23a86c8601f5dead53c7b241': 0.0010178440811610464, 'b78bdac2d66434f67db2a71b6f893639': 0.0023564150659103078, '68c7aa8355d0b7c6e75c67d5df51d569': 0.001333269713284689, 'e9e060e5e0e46911cad92b8292aeefd7': 0.005682962769800513, '2b335f368deba69c6c95c18da31dc5f4': 0.0033530540612130657, 'f2cd13764c9588bd921f3a53138830da': 0.0016142370908978111, 'e1abbababbc410f2f1faa24f6ccbc7f9': 0.007244187146052604, '8fabb679415fe6a9969015076873e211': 0.0034511275833076487, 'cd1f95189b8375347f827f4a8b08dcf7': 0.02242967860572144, 'b180a2455b236c103cf0bfe620095736': 0.011869546298707779, '6dbf54dfd0a3207126af074af10be296': 0.0012298949297347315, 'dc22433569281cc665fba3df53e3f566': 0.0022159313720991475, '7767ca8c82d1d254c5d3228f43b2b213': 0.0015029103901417977, 'a27f37aae2a34101f8a61c6f0b1cd246': 0.009810002424804308, '54e41d7748bdb8fe71a73a47ad58423e': 0.0028441320206325426, 'b50c901a9773cf8216278d2bb4e70644': 0.001468452135631277, 'b7806c4f83108800a9c32dc83c148d95': 0.0027725648558608196, '919c50490dbc9552a946f26b32c4ae12': 0.002735455955608815, '8c86a02bd0f2c7a90bb40b735577a623': 0.0068465917962188955, '5a6520a634bb27352c524ba237fd0d64': 0.0066424928548420685, '911ddc4e1da558630158fa05fba14992': 0.0013677279778044075, '49d8ed77132802ef1ad7036f31e0117a': 0.004137642207942139, 'fe74d2e267ad3ebb8fbfe24bbb464049': 0.0041933055483109475, 'e2c63d5718cf9ea95828084c3b843443': 0.005921519975697058})
0 member biomasses will merge into the community biomass {}
Neither carbon consumption nor oxygen consumption are defined in 10AB_comm
Community objective 1.0*bio1 - 1.0*bio1_reverse_b18f7

In [15]:
from json import load
abundances = load(open("modeling_files/ASVset_abundances.json", 'r'))
list(list(abundances.values())[0].values())[0]

0.0035438998239284624

## Test that the models are operational

In [1]:
from cobra.io import read_sbml_model
from glob import glob

for path in glob("models/*_comm.xml"):
    print(path.split("/")[-1])
    model = read_sbml_model(path)
    break

'' is not a valid SBML 'SId'.

10AB_comm.xml

In [3]:
print(model.objective)
display(model.summary())

1.0*bio1 - 1.0*bio1_reverse_b18f7

In [4]:
model.reactions.bio1.reaction

'cpd11416_c135 --> cpd11416_c0'

In [11]:
bioReactions = []
for rxn in model.reactions:
    if "bio" in rxn.id:
        bioReactions.append(rxn.id)
bioReactions = sorted(bioReactions)
print(len(bioReactions), bioReactions)

136 ['bio1', 'bio10', 'bio100', 'bio101', 'bio102', 'bio103', 'bio104', 'bio105', 'bio106', 'bio107', 'bio108', 'bio109', 'bio11', 'bio110', 'bio111', 'bio112', 'bio113', 'bio114', 'bio115', 'bio116', 'bio117', 'bio118', 'bio119', 'bio12', 'bio120', 'bio121', 'bio122', 'bio123', 'bio124', 'bio125', 'bio126', 'bio127', 'bio128', 'bio129', 'bio13', 'bio130', 'bio131', 'bio132', 'bio133', 'bio134', 'bio135', 'bio136', 'bio14', 'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio20', 'bio21', 'bio22', 'bio23', 'bio24', 'bio25', 'bio26', 'bio27', 'bio28', 'bio29', 'bio3', 'bio30', 'bio31', 'bio32', 'bio33', 'bio34', 'bio35', 'bio36', 'bio37', 'bio38', 'bio39', 'bio4', 'bio40', 'bio41', 'bio42', 'bio43', 'bio44', 'bio45', 'bio46', 'bio47', 'bio48', 'bio49', 'bio5', 'bio50', 'bio51', 'bio52', 'bio53', 'bio54', 'bio55', 'bio56', 'bio57', 'bio58', 'bio59', 'bio6', 'bio60', 'bio61', 'bio62', 'bio63', 'bio64', 'bio65', 'bio66', 'bio67', 'bio68', 'bio69', 'bio7', 'bio70', 'bio71', 'bio72', 'bio73', 'bio74', 'bio75', 'bio76', 'bio77', 'bio78', 'bio79', 'bio8', 'bio80', 'bio81', 'bio82', 'bio83', 'bio84', 'bio85', 'bio86', 'bio87', 'bio88', 'bio89', 'bio9', 'bio90', 'bio91', 'bio92', 'bio93', 'bio94', 'bio95', 'bio96', 'bio97', 'bio98', 'bio99']

In [12]:
bioCompounds = []
for cpd in model.metabolites:
    if "cpd11416" in cpd.id:
        bioCompounds.append(cpd.id)
bioCompounds = sorted(bioCompounds)
print(len(bioCompounds), bioCompounds)

136 ['cpd11416_c0', 'cpd11416_c1', 'cpd11416_c10', 'cpd11416_c100', 'cpd11416_c101', 'cpd11416_c102', 'cpd11416_c103', 'cpd11416_c104', 'cpd11416_c105', 'cpd11416_c106', 'cpd11416_c107', 'cpd11416_c108', 'cpd11416_c109', 'cpd11416_c11', 'cpd11416_c110', 'cpd11416_c111', 'cpd11416_c112', 'cpd11416_c113', 'cpd11416_c114', 'cpd11416_c115', 'cpd11416_c116', 'cpd11416_c117', 'cpd11416_c118', 'cpd11416_c119', 'cpd11416_c12', 'cpd11416_c120', 'cpd11416_c121', 'cpd11416_c122', 'cpd11416_c123', 'cpd11416_c124', 'cpd11416_c125', 'cpd11416_c126', 'cpd11416_c127', 'cpd11416_c128', 'cpd11416_c129', 'cpd11416_c13', 'cpd11416_c130', 'cpd11416_c131', 'cpd11416_c132', 'cpd11416_c133', 'cpd11416_c134', 'cpd11416_c135', 'cpd11416_c14', 'cpd11416_c15', 'cpd11416_c16', 'cpd11416_c17', 'cpd11416_c18', 'cpd11416_c19', 'cpd11416_c2', 'cpd11416_c20', 'cpd11416_c21', 'cpd11416_c22', 'cpd11416_c23', 'cpd11416_c24', 'cpd11416_c25', 'cpd11416_c26', 'cpd11416_c27', 'cpd11416_c28', 'cpd11416_c29', 'cpd11416_c3', 'cpd11416_c30', 'cpd11416_c31', 'cpd11416_c32', 'cpd11416_c33', 'cpd11416_c34', 'cpd11416_c35', 'cpd11416_c36', 'cpd11416_c37', 'cpd11416_c38', 'cpd11416_c39', 'cpd11416_c4', 'cpd11416_c40', 'cpd11416_c41', 'cpd11416_c42', 'cpd11416_c43', 'cpd11416_c44', 'cpd11416_c45', 'cpd11416_c46', 'cpd11416_c47', 'cpd11416_c48', 'cpd11416_c49', 'cpd11416_c5', 'cpd11416_c50', 'cpd11416_c51', 'cpd11416_c52', 'cpd11416_c53', 'cpd11416_c54', 'cpd11416_c55', 'cpd11416_c56', 'cpd11416_c57', 'cpd11416_c58', 'cpd11416_c59', 'cpd11416_c6', 'cpd11416_c60', 'cpd11416_c61', 'cpd11416_c62', 'cpd11416_c63', 'cpd11416_c64', 'cpd11416_c65', 'cpd11416_c66', 'cpd11416_c67', 'cpd11416_c68', 'cpd11416_c69', 'cpd11416_c7', 'cpd11416_c70', 'cpd11416_c71', 'cpd11416_c72', 'cpd11416_c73', 'cpd11416_c74', 'cpd11416_c75', 'cpd11416_c76', 'cpd11416_c77', 'cpd11416_c78', 'cpd11416_c79', 'cpd11416_c8', 'cpd11416_c80', 'cpd11416_c81', 'cpd11416_c82', 'cpd11416_c83', 'cpd11416_c84', 'cpd11416_c85', 'cpd11416_c86', 'cpd11416_c87', 'cpd11416_c88', 'cpd11416_c89', 'cpd11416_c9', 'cpd11416_c90', 'cpd11416_c91', 'cpd11416_c92', 'cpd11416_c93', 'cpd11416_c94', 'cpd11416_c95', 'cpd11416_c96', 'cpd11416_c97', 'cpd11416_c98', 'cpd11416_c99']

In [5]:
print(path)
for rxn in model.reactions:
    if "bio" in rxn.id:
        print(rxn.id, rxn.reaction)

models/D34_comm.xml
bio9 40.0 cpd00001_c8 + 40.0 cpd00002_c8 + 0.00280457955290608 cpd00003_c8 + 0.00280457955290608 cpd00006_c8 + 0.00280457955290608 cpd00010_c8 + 0.00280457955290608 cpd00015_c8 + 0.00280457955290608 cpd00016_c8 + 0.00280457955290608 cpd00017_c8 + 0.00280457955290608 cpd00028_c8 + 0.00280457955290608 cpd00030_c8 + 0.00280457955290608 cpd00034_c8 + 0.00280457955290608 cpd00037_c8 + 0.00280457955290608 cpd00042_c8 + 0.00280457955290608 cpd00048_c8 + 0.00280457955290608 cpd00050_c8 + 0.00280457955290608 cpd00056_c8 + 0.00280457955290608 cpd00058_c8 + 0.00280457955290608 cpd00063_c8 + 0.00280457955290608 cpd00087_c8 + 0.00280457955290608 cpd00099_c8 + 0.00280457955290608 cpd00104_c8 + 0.00280457955290608 cpd00118_c8 + 0.00280457955290608 cpd00149_c8 + 0.00280457955290608 cpd00166_c8 + 0.00280457955290608 cpd00201_c8 + 0.00280457955290608 cpd00205_c8 + 0.00280457955290608 cpd00220_c8 + 0.00280457955290608 cpd00254_c8 + 0.00280457955290608 cpd00264_c8 + 0.00280457955290608 cpd00345_c8 + 0.00280457955290608 cpd00557_c8 + 0.0250024211878531 cpd02229_c8 + 0.00280457955290608 cpd10515_c8 + 0.00280457955290608 cpd10516_c8 + 0.031 cpd11461_c8 + 0.21 cpd11462_c8 + 0.563 cpd11463_c8 + 0.00280457955290608 cpd11493_c8 + 0.00280457955290608 cpd15352_c8 + 0.0250024211878531 cpd15432_c8 + 0.00280457955290608 cpd15500_c8 + 0.0311018446074631 cpd15533_c8 + 0.0311018446074631 cpd15540_c8 + 0.00280457955290608 cpd15560_c8 + 0.0250024211878531 cpd15665_c8 + 0.0311018446074631 cpd15793_c8 --> 40.0 cpd00008_c8 + 39.9971954204471 cpd00009_c8 + 40.0 cpd00067_c8 + 0.00280457955290608 cpd01997_c8 + 0.00280457955290608 cpd03422_c8 + cpd11416_c8 + 0.00280457955290608 cpd12370_c8 + 0.0250024211878531 cpd15666_c8
bio16 40.0 cpd00001_c15 + 40.0 cpd00002_c15 + 0.00280457955290608 cpd00003_c15 + 0.00280457955290608 cpd00006_c15 + 0.00280457955290608 cpd00010_c15 + 0.00280457955290608 cpd00015_c15 + 0.00280457955290608 cpd00016_c15 + 0.00280457955290608 cpd00017_c15 + 0.00280457955290608 cpd00028_c15 + 0.00280457955290608 cpd00030_c15 + 0.00280457955290608 cpd00034_c15 + 0.00280457955290608 cpd00037_c15 + 0.00280457955290608 cpd00042_c15 + 0.00280457955290608 cpd00048_c15 + 0.00280457955290608 cpd00050_c15 + 0.00280457955290608 cpd00056_c15 + 0.00280457955290608 cpd00058_c15 + 0.00280457955290608 cpd00063_c15 + 0.00280457955290608 cpd00087_c15 + 0.00280457955290608 cpd00099_c15 + 0.00280457955290608 cpd00104_c15 + 0.00280457955290608 cpd00118_c15 + 0.00280457955290608 cpd00149_c15 + 0.00280457955290608 cpd00166_c15 + 0.00280457955290608 cpd00201_c15 + 0.00280457955290608 cpd00205_c15 + 0.00280457955290608 cpd00220_c15 + 0.00280457955290608 cpd00254_c15 + 0.00280457955290608 cpd00264_c15 + 0.00280457955290608 cpd00345_c15 + 0.00280457955290608 cpd00557_c15 + 0.0250024211878531 cpd02229_c15 + 0.00280457955290608 cpd10515_c15 + 0.00280457955290608 cpd10516_c15 + 0.031 cpd11461_c15 + 0.21 cpd11462_c15 + 0.563 cpd11463_c15 + 0.00280457955290608 cpd11493_c15 + 0.00280457955290608 cpd15352_c15 + 0.0250024211878531 cpd15432_c15 + 0.00280457955290608 cpd15500_c15 + 0.0311018446074631 cpd15533_c15 + 0.0311018446074631 cpd15540_c15 + 0.00280457955290608 cpd15560_c15 + 0.0250024211878531 cpd15665_c15 + 0.0311018446074631 cpd15793_c15 --> 40.0 cpd00008_c15 + 39.9971954204471 cpd00009_c15 + 40.0 cpd00067_c15 + 0.00280457955290608 cpd01997_c15 + 0.00280457955290608 cpd03422_c15 + cpd11416_c15 + 0.00280457955290608 cpd12370_c15 + 0.0250024211878531 cpd15666_c15
bio32 40.0 cpd00001_c31 + 40.0 cpd00002_c31 + 0.00280457955290608 cpd00003_c31 + 0.00280457955290608 cpd00006_c31 + 0.00280457955290608 cpd00010_c31 + 0.00280457955290608 cpd00015_c31 + 0.00280457955290608 cpd00016_c31 + 0.00280457955290608 cpd00017_c31 + 0.00280457955290608 cpd00028_c31 + 0.00280457955290608 cpd00030_c31 + 0.00280457955290608 cpd00034_c31 + 0.00280457955290608 cpd00037_c31 + 0.00280457955290608 cpd00042_c31 + 0.00280457955290608 cpd00048_c31 + 0.00280457955290608 cpd00050_c31 + 0.00280457955290608 cpd00056_c31 + 0.00280457955290608 cpd00058_c31 + 0.00280457955290608 cpd00063_c31 + 0.00280457955290608 cpd00087_c31 + 0.00280457955290608 cpd00099_c31 + 0.00280457955290608 cpd00104_c31 + 0.00280457955290608 cpd00118_c31 + 0.00280457955290608 cpd00149_c31 + 0.00280457955290608 cpd00166_c31 + 0.00280457955290608 cpd00201_c31 + 0.00280457955290608 cpd00205_c31 + 0.00280457955290608 cpd00220_c31 + 0.00280457955290608 cpd00254_c31 + 0.00280457955290608 cpd00264_c31 + 0.00280457955290608 cpd00345_c31 + 0.00280457955290608 cpd00557_c31 + 0.0250024211878531 cpd02229_c31 + 0.00280457955290608 cpd10515_c31 + 0.00280457955290608 cpd10516_c31 + 0.031 cpd11461_c31 + 0.21 cpd11462_c31 + 0.563 cpd11463_c31 + 0.00280457955290608 cpd11493_c31 + 0.00280457955290608 cpd15352_c31 + 0.0250024211878531 cpd15432_c31 + 0.00280457955290608 cpd15500_c31 + 0.0311018446074631 cpd15533_c31 + 0.0311018446074631 cpd15540_c31 + 0.00280457955290608 cpd15560_c31 + 0.0250024211878531 cpd15665_c31 + 0.0311018446074631 cpd15793_c31 --> 40.0 cpd00008_c31 + 39.9971954204471 cpd00009_c31 + 40.0 cpd00067_c31 + 0.00280457955290608 cpd01997_c31 + 0.00280457955290608 cpd03422_c31 + cpd11416_c31 + 0.00280457955290608 cpd12370_c31 + 0.0250024211878531 cpd15666_c31
bio48 40.0 cpd00001_c47 + 40.0 cpd00002_c47 + 0.00280457955290608 cpd00003_c47 + 0.00280457955290608 cpd00006_c47 + 0.00280457955290608 cpd00010_c47 + 0.00280457955290608 cpd00015_c47 + 0.00280457955290608 cpd00016_c47 + 0.00280457955290608 cpd00017_c47 + 0.00280457955290608 cpd00028_c47 + 0.00280457955290608 cpd00030_c47 + 0.00280457955290608 cpd00034_c47 + 0.00280457955290608 cpd00037_c47 + 0.00280457955290608 cpd00042_c47 + 0.00280457955290608 cpd00048_c47 + 0.00280457955290608 cpd00050_c47 + 0.00280457955290608 cpd00056_c47 + 0.00280457955290608 cpd00058_c47 + 0.00280457955290608 cpd00063_c47 + 0.00280457955290608 cpd00087_c47 + 0.00280457955290608 cpd00099_c47 + 0.00280457955290608 cpd00104_c47 + 0.00280457955290608 cpd00118_c47 + 0.00280457955290608 cpd00149_c47 + 0.00280457955290608 cpd00166_c47 + 0.00280457955290608 cpd00201_c47 + 0.00280457955290608 cpd00205_c47 + 0.00280457955290608 cpd00220_c47 + 0.00280457955290608 cpd00254_c47 + 0.00280457955290608 cpd00264_c47 + 0.00280457955290608 cpd00345_c47 + 0.00280457955290608 cpd00557_c47 + 0.0250024211878531 cpd02229_c47 + 0.00280457955290608 cpd10515_c47 + 0.00280457955290608 cpd10516_c47 + 0.031 cpd11461_c47 + 0.21 cpd11462_c47 + 0.563 cpd11463_c47 + 0.00280457955290608 cpd11493_c47 + 0.00280457955290608 cpd15352_c47 + 0.0250024211878531 cpd15432_c47 + 0.00280457955290608 cpd15500_c47 + 0.0311018446074631 cpd15533_c47 + 0.0311018446074631 cpd15540_c47 + 0.00280457955290608 cpd15560_c47 + 0.0250024211878531 cpd15665_c47 + 0.0311018446074631 cpd15793_c47 --> 40.0 cpd00008_c47 + 39.9971954204471 cpd00009_c47 + 40.0 cpd00067_c47 + 0.00280457955290608 cpd01997_c47 + 0.00280457955290608 cpd03422_c47 + cpd11416_c47 + 0.00280457955290608 cpd12370_c47 + 0.0250024211878531 cpd15666_c47
bio2 40.0 cpd00001_c1 + 40.0 cpd00002_c1 + 0.00280457955290608 cpd00003_c1 + 0.00280457955290608 cpd00006_c1 + 0.00280457955290608 cpd00010_c1 + 0.00280457955290608 cpd00015_c1 + 0.00280457955290608 cpd00016_c1 + 0.00280457955290608 cpd00017_c1 + 0.00280457955290608 cpd00028_c1 + 0.00280457955290608 cpd00030_c1 + 0.00280457955290608 cpd00034_c1 + 0.00280457955290608 cpd00037_c1 + 0.00280457955290608 cpd00042_c1 + 0.00280457955290608 cpd00048_c1 + 0.00280457955290608 cpd00050_c1 + 0.00280457955290608 cpd00056_c1 + 0.00280457955290608 cpd00058_c1 + 0.00280457955290608 cpd00063_c1 + 0.00280457955290608 cpd00087_c1 + 0.00280457955290608 cpd00099_c1 + 0.00280457955290608 cpd00104_c1 + 0.00280457955290608 cpd00118_c1 + 0.00280457955290608 cpd00149_c1 + 0.00280457955290608 cpd00166_c1 + 0.00280457955290608 cpd00201_c1 + 0.00280457955290608 cpd00205_c1 + 0.00280457955290608 cpd00220_c1 + 0.00280457955290608 cpd00254_c1 + 0.00280457955290608 cpd00264_c1 + 0.00280457955290608 cpd00345_c1 + 0.00280457955290608 cpd00557_c1 + 0.0250024211878531 cpd02229_c1 + 0.00280457955290608 cpd10515_c1 + 0.00280457955290608 cpd10516_c1 + 0.031 cpd11461_c1 + 0.21 cpd11462_c1 + 0.563 cpd11463_c1 + 0.00280457955290608 cpd11493_c1 + 0.00280457955290608 cpd15352_c1 + 0.0250024211878531 cpd15432_c1 + 0.00280457955290608 cpd15500_c1 + 0.0311018446074631 cpd15533_c1 + 0.0311018446074631 cpd15540_c1 + 0.00280457955290608 cpd15560_c1 + 0.0250024211878531 cpd15665_c1 + 0.0311018446074631 cpd15793_c1 --> 40.0 cpd00008_c1 + 39.9971954204471 cpd00009_c1 + 40.0 cpd00067_c1 + 0.00280457955290608 cpd01997_c1 + 0.00280457955290608 cpd03422_c1 + cpd11416_c1 + 0.00280457955290608 cpd12370_c1 + 0.0250024211878531 cpd15666_c1
bio8 40.0 cpd00001_c7 + 40.0 cpd00002_c7 + 0.00280457955290608 cpd00003_c7 + 0.00280457955290608 cpd00006_c7 + 0.00280457955290608 cpd00010_c7 + 0.00280457955290608 cpd00015_c7 + 0.00280457955290608 cpd00016_c7 + 0.00280457955290608 cpd00017_c7 + 0.00280457955290608 cpd00028_c7 + 0.00280457955290608 cpd00030_c7 + 0.00280457955290608 cpd00034_c7 + 0.00280457955290608 cpd00037_c7 + 0.00280457955290608 cpd00042_c7 + 0.00280457955290608 cpd00048_c7 + 0.00280457955290608 cpd00050_c7 + 0.00280457955290608 cpd00056_c7 + 0.00280457955290608 cpd00058_c7 + 0.00280457955290608 cpd00063_c7 + 0.00280457955290608 cpd00087_c7 + 0.00280457955290608 cpd00099_c7 + 0.00280457955290608 cpd00104_c7 + 0.00280457955290608 cpd00118_c7 + 0.00280457955290608 cpd00149_c7 + 0.00280457955290608 cpd00166_c7 + 0.00280457955290608 cpd00201_c7 + 0.00280457955290608 cpd00205_c7 + 0.00280457955290608 cpd00220_c7 + 0.00280457955290608 cpd00254_c7 + 0.00280457955290608 cpd00264_c7 + 0.00280457955290608 cpd00345_c7 + 0.00280457955290608 cpd00557_c7 + 0.0250024211878531 cpd02229_c7 + 0.00280457955290608 cpd10515_c7 + 0.00280457955290608 cpd10516_c7 + 0.031 cpd11461_c7 + 0.21 cpd11462_c7 + 0.563 cpd11463_c7 + 0.00280457955290608 cpd11493_c7 + 0.00280457955290608 cpd15352_c7 + 0.0250024211878531 cpd15432_c7 + 0.00280457955290608 cpd15500_c7 + 0.0311018446074631 cpd15533_c7 + 0.0311018446074631 cpd15540_c7 + 0.00280457955290608 cpd15560_c7 + 0.0250024211878531 cpd15665_c7 + 0.0311018446074631 cpd15793_c7 --> 40.0 cpd00008_c7 + 39.9971954204471 cpd00009_c7 + 40.0 cpd00067_c7 + 0.00280457955290608 cpd01997_c7 + 0.00280457955290608 cpd03422_c7 + cpd11416_c7 + 0.00280457955290608 cpd12370_c7 + 0.0250024211878531 cpd15666_c7
bio39 40.0 cpd00001_c38 + 40.0 cpd00002_c38 + 0.00280457955290608 cpd00003_c38 + 0.00280457955290608 cpd00006_c38 + 0.00280457955290608 cpd00010_c38 + 0.00280457955290608 cpd00015_c38 + 0.00280457955290608 cpd00016_c38 + 0.00280457955290608 cpd00017_c38 + 0.00280457955290608 cpd00028_c38 + 0.00280457955290608 cpd00030_c38 + 0.00280457955290608 cpd00034_c38 + 0.00280457955290608 cpd00037_c38 + 0.00280457955290608 cpd00042_c38 + 0.00280457955290608 cpd00048_c38 + 0.00280457955290608 cpd00050_c38 + 0.00280457955290608 cpd00056_c38 + 0.00280457955290608 cpd00058_c38 + 0.00280457955290608 cpd00063_c38 + 0.00280457955290608 cpd00087_c38 + 0.00280457955290608 cpd00099_c38 + 0.00280457955290608 cpd00104_c38 + 0.00280457955290608 cpd00118_c38 + 0.00280457955290608 cpd00149_c38 + 0.00280457955290608 cpd00166_c38 + 0.00280457955290608 cpd00201_c38 + 0.00280457955290608 cpd00205_c38 + 0.00280457955290608 cpd00220_c38 + 0.00280457955290608 cpd00254_c38 + 0.00280457955290608 cpd00264_c38 + 0.00280457955290608 cpd00345_c38 + 0.00280457955290608 cpd00557_c38 + 0.0250024211878531 cpd02229_c38 + 0.00280457955290608 cpd10515_c38 + 0.00280457955290608 cpd10516_c38 + 0.031 cpd11461_c38 + 0.21 cpd11462_c38 + 0.563 cpd11463_c38 + 0.00280457955290608 cpd11493_c38 + 0.00280457955290608 cpd15352_c38 + 0.0250024211878531 cpd15432_c38 + 0.00280457955290608 cpd15500_c38 + 0.0311018446074631 cpd15533_c38 + 0.0311018446074631 cpd15540_c38 + 0.00280457955290608 cpd15560_c38 + 0.0250024211878531 cpd15665_c38 + 0.0311018446074631 cpd15793_c38 --> 40.0 cpd00008_c38 + 39.9971954204471 cpd00009_c38 + 40.0 cpd00067_c38 + 0.00280457955290608 cpd01997_c38 + 0.00280457955290608 cpd03422_c38 + cpd11416_c38 + 0.00280457955290608 cpd12370_c38 + 0.0250024211878531 cpd15666_c38
bio38 40.0 cpd00001_c37 + 40.0 cpd00002_c37 + 0.00280457955290608 cpd00003_c37 + 0.00280457955290608 cpd00006_c37 + 0.00280457955290608 cpd00010_c37 + 0.00280457955290608 cpd00015_c37 + 0.00280457955290608 cpd00016_c37 + 0.00280457955290608 cpd00017_c37 + 0.00280457955290608 cpd00028_c37 + 0.00280457955290608 cpd00030_c37 + 0.00280457955290608 cpd00034_c37 + 0.00280457955290608 cpd00037_c37 + 0.00280457955290608 cpd00042_c37 + 0.00280457955290608 cpd00048_c37 + 0.00280457955290608 cpd00050_c37 + 0.00280457955290608 cpd00056_c37 + 0.00280457955290608 cpd00058_c37 + 0.00280457955290608 cpd00063_c37 + 0.00280457955290608 cpd00087_c37 + 0.00280457955290608 cpd00099_c37 + 0.00280457955290608 cpd00104_c37 + 0.00280457955290608 cpd00118_c37 + 0.00280457955290608 cpd00149_c37 + 0.00280457955290608 cpd00166_c37 + 0.00280457955290608 cpd00201_c37 + 0.00280457955290608 cpd00205_c37 + 0.00280457955290608 cpd00220_c37 + 0.00280457955290608 cpd00254_c37 + 0.00280457955290608 cpd00264_c37 + 0.00280457955290608 cpd00345_c37 + 0.00280457955290608 cpd00557_c37 + 0.0250024211878531 cpd02229_c37 + 0.00280457955290608 cpd10515_c37 + 0.00280457955290608 cpd10516_c37 + 0.031 cpd11461_c37 + 0.21 cpd11462_c37 + 0.563 cpd11463_c37 + 0.00280457955290608 cpd11493_c37 + 0.00280457955290608 cpd15352_c37 + 0.0250024211878531 cpd15432_c37 + 0.00280457955290608 cpd15500_c37 + 0.0311018446074631 cpd15533_c37 + 0.0311018446074631 cpd15540_c37 + 0.00280457955290608 cpd15560_c37 + 0.0250024211878531 cpd15665_c37 + 0.0311018446074631 cpd15793_c37 --> 40.0 cpd00008_c37 + 39.9971954204471 cpd00009_c37 + 40.0 cpd00067_c37 + 0.00280457955290608 cpd01997_c37 + 0.00280457955290608 cpd03422_c37 + cpd11416_c37 + 0.00280457955290608 cpd12370_c37 + 0.0250024211878531 cpd15666_c37
bio56 40.0 cpd00001_c55 + 40.0 cpd00002_c55 + 0.00280457955290608 cpd00003_c55 + 0.00280457955290608 cpd00006_c55 + 0.00280457955290608 cpd00010_c55 + 0.00280457955290608 cpd00015_c55 + 0.00280457955290608 cpd00016_c55 + 0.00280457955290608 cpd00017_c55 + 0.00280457955290608 cpd00028_c55 + 0.00280457955290608 cpd00030_c55 + 0.00280457955290608 cpd00034_c55 + 0.00280457955290608 cpd00037_c55 + 0.00280457955290608 cpd00042_c55 + 0.00280457955290608 cpd00048_c55 + 0.00280457955290608 cpd00050_c55 + 0.00280457955290608 cpd00056_c55 + 0.00280457955290608 cpd00058_c55 + 0.00280457955290608 cpd00063_c55 + 0.00280457955290608 cpd00087_c55 + 0.00280457955290608 cpd00099_c55 + 0.00280457955290608 cpd00104_c55 + 0.00280457955290608 cpd00118_c55 + 0.00280457955290608 cpd00149_c55 + 0.00280457955290608 cpd00166_c55 + 0.00280457955290608 cpd00201_c55 + 0.00280457955290608 cpd00205_c55 + 0.00280457955290608 cpd00220_c55 + 0.00280457955290608 cpd00254_c55 + 0.00280457955290608 cpd00264_c55 + 0.00280457955290608 cpd00345_c55 + 0.00280457955290608 cpd00557_c55 + 0.0250024211878531 cpd02229_c55 + 0.00280457955290608 cpd10515_c55 + 0.00280457955290608 cpd10516_c55 + 0.031 cpd11461_c55 + 0.21 cpd11462_c55 + 0.563 cpd11463_c55 + 0.00280457955290608 cpd11493_c55 + 0.00280457955290608 cpd15352_c55 + 0.0250024211878531 cpd15432_c55 + 0.00280457955290608 cpd15500_c55 + 0.0311018446074631 cpd15533_c55 + 0.0311018446074631 cpd15540_c55 + 0.00280457955290608 cpd15560_c55 + 0.0250024211878531 cpd15665_c55 + 0.0311018446074631 cpd15793_c55 --> 40.0 cpd00008_c55 + 39.9971954204471 cpd00009_c55 + 40.0 cpd00067_c55 + 0.00280457955290608 cpd01997_c55 + 0.00280457955290608 cpd03422_c55 + cpd11416_c55 + 0.00280457955290608 cpd12370_c55 + 0.0250024211878531 cpd15666_c55
bio30 40.0 cpd00001_c29 + 40.0 cpd00002_c29 + 0.00280457955290608 cpd00003_c29 + 0.00280457955290608 cpd00006_c29 + 0.00280457955290608 cpd00010_c29 + 0.00280457955290608 cpd00015_c29 + 0.00280457955290608 cpd00016_c29 + 0.00280457955290608 cpd00017_c29 + 0.00280457955290608 cpd00028_c29 + 0.00280457955290608 cpd00030_c29 + 0.00280457955290608 cpd00034_c29 + 0.00280457955290608 cpd00037_c29 + 0.00280457955290608 cpd00042_c29 + 0.00280457955290608 cpd00048_c29 + 0.00280457955290608 cpd00050_c29 + 0.00280457955290608 cpd00056_c29 + 0.00280457955290608 cpd00058_c29 + 0.00280457955290608 cpd00063_c29 + 0.00280457955290608 cpd00087_c29 + 0.00280457955290608 cpd00099_c29 + 0.00280457955290608 cpd00104_c29 + 0.00280457955290608 cpd00118_c29 + 0.00280457955290608 cpd00149_c29 + 0.00280457955290608 cpd00166_c29 + 0.00280457955290608 cpd00201_c29 + 0.00280457955290608 cpd00205_c29 + 0.00280457955290608 cpd00220_c29 + 0.00280457955290608 cpd00254_c29 + 0.00280457955290608 cpd00264_c29 + 0.00280457955290608 cpd00345_c29 + 0.00280457955290608 cpd00557_c29 + 0.0250024211878531 cpd02229_c29 + 0.00280457955290608 cpd10515_c29 + 0.00280457955290608 cpd10516_c29 + 0.031 cpd11461_c29 + 0.21 cpd11462_c29 + 0.563 cpd11463_c29 + 0.00280457955290608 cpd11493_c29 + 0.00280457955290608 cpd15352_c29 + 0.0250024211878531 cpd15432_c29 + 0.00280457955290608 cpd15500_c29 + 0.0311018446074631 cpd15533_c29 + 0.0311018446074631 cpd15540_c29 + 0.00280457955290608 cpd15560_c29 + 0.0250024211878531 cpd15665_c29 + 0.0311018446074631 cpd15793_c29 --> 40.0 cpd00008_c29 + 39.9971954204471 cpd00009_c29 + 40.0 cpd00067_c29 + 0.00280457955290608 cpd01997_c29 + 0.00280457955290608 cpd03422_c29 + cpd11416_c29 + 0.00280457955290608 cpd12370_c29 + 0.0250024211878531 cpd15666_c29
bio22 40.0 cpd00001_c21 + 40.0 cpd00002_c21 + 0.00280457955290608 cpd00003_c21 + 0.00280457955290608 cpd00006_c21 + 0.00280457955290608 cpd00010_c21 + 0.00280457955290608 cpd00015_c21 + 0.00280457955290608 cpd00016_c21 + 0.00280457955290608 cpd00017_c21 + 0.00280457955290608 cpd00028_c21 + 0.00280457955290608 cpd00030_c21 + 0.00280457955290608 cpd00034_c21 + 0.00280457955290608 cpd00037_c21 + 0.00280457955290608 cpd00042_c21 + 0.00280457955290608 cpd00048_c21 + 0.00280457955290608 cpd00050_c21 + 0.00280457955290608 cpd00056_c21 + 0.00280457955290608 cpd00058_c21 + 0.00280457955290608 cpd00063_c21 + 0.00280457955290608 cpd00087_c21 + 0.00280457955290608 cpd00099_c21 + 0.00280457955290608 cpd00104_c21 + 0.00280457955290608 cpd00118_c21 + 0.00280457955290608 cpd00149_c21 + 0.00280457955290608 cpd00166_c21 + 0.00280457955290608 cpd00201_c21 + 0.00280457955290608 cpd00205_c21 + 0.00280457955290608 cpd00220_c21 + 0.00280457955290608 cpd00254_c21 + 0.00280457955290608 cpd00264_c21 + 0.00280457955290608 cpd00345_c21 + 0.00280457955290608 cpd00557_c21 + 0.0250024211878531 cpd02229_c21 + 0.00280457955290608 cpd10515_c21 + 0.00280457955290608 cpd10516_c21 + 0.031 cpd11461_c21 + 0.21 cpd11462_c21 + 0.563 cpd11463_c21 + 0.00280457955290608 cpd11493_c21 + 0.00280457955290608 cpd15352_c21 + 0.0250024211878531 cpd15432_c21 + 0.00280457955290608 cpd15500_c21 + 0.0311018446074631 cpd15533_c21 + 0.0311018446074631 cpd15540_c21 + 0.00280457955290608 cpd15560_c21 + 0.0250024211878531 cpd15665_c21 + 0.0311018446074631 cpd15793_c21 --> 40.0 cpd00008_c21 + 39.9971954204471 cpd00009_c21 + 40.0 cpd00067_c21 + 0.00280457955290608 cpd01997_c21 + 0.00280457955290608 cpd03422_c21 + cpd11416_c21 + 0.00280457955290608 cpd12370_c21 + 0.0250024211878531 cpd15666_c21

# Conduct community modeling

## Constraints

#### convert into MSIDs

In [ ]:
mapping = {"Media Acetate (mol/L)": "cpd00029", "Media Propionate (mol/L)": "cpd00141", "Media Butyrate (mol/L)": "cpd00211",
          "Waste Effluent Acetate (mol/L)": "cpd00029", "Waste Effluent Propionate (mol/L)": "cpd00141",
           "Waste Effluent Butyrate (mol/L)": "cpd00211"}
total_c = ["Waste Effluent Dissolved Inorganic Carbon (mol C/L)", "Waste Effluent Dissolved Organic Carbon (mol C/L)"]

In [ ]:
# from modelseedpy.biochem import from_local

# {}

### loading the media