# create models from ASVset genome objects

In [1]:
from load_genomes_to_modelseedpy import GenomeLoader
from cobra.io import write_sbml_model
# from glob import glob
from tqdm import tqdm
import os

loader = GenomeLoader()
# genome_ids = loader.list_available_genomes()#[:10]

def write_model(gID):
    model = loader.build_model(gID, printing=False)
    write_sbml_model(model, f'models/{gID}.xml')

# for genome_id in tqdm(genome_ids):
#     model_path = f'models/{genome_id}.xml'
#     if os.path.exists(model_path):  continue
#     try:
#         model = loader.build_model(genome_id, printing=False)
#         write_sbml_model(model, model_path)
#         # print(f"✓ {genome_id}") 
#     except Exception as e:
#         print(f"✗ {genome_id}: {e}")


# parallelize the effort
args = [gID for gID in loader.list_available_genomes() if not os.path.exists(f'models/{gID}.xml')]#[:2]
print(len(args), "will be processed")
parallelize = False
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = int(cpu_count()/8)
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(write_model, args)
    
    print(f"missing iterativeIDs", missing_iterativeIDs)
    print(f"missing IDs", missing_IDs)
else:
    for arg in args:
        # print(arg)
        write_model(arg)

100%|██████████| 1698/1698 [1:21:00<00:00,  2.86s/it]

## Gapfill the models in minimal media

## Define the metabolite-centered phenotypes

In [12]:
%run util.py
from json import load
from numpy import mean

# microbiome_path = "/Users/andrewfreiburger/Documents/Research/MicrobiomeNotebooks/digestor"
microbiome_path = "../MicrobiomeNotebooks"
metabolites = load(open(f"{microbiome_path}/digestor/metabolites.json", 'r'))
metaboliteIDs = list(metabolites.keys())

media_nar = 207617
metabolites = util.msrecon.get_media(f"{media_nar}/Wolfe").mediacompounds
auxo_media = util.msrecon.get_media(f"{media_nar}/AuxoMedia")
anaerobicPyruvate = util.msrecon.get_media(f"{media_nar}/PyruateMinimalAnaerobic")
# metabolites
metaboliteIDs = [cpd['id'] for cpd in metabolites] + ["cpd00011", "cpd11640", "cpd01024"]  # experimental media + CO2,H2,CH4

#TODO:  Why is growth only performed for the non-base media and uptake/excretion only performed for the base media?
uptake_phenoset = util.create_phenotypeset_from_compounds(
    metaboliteIDs, base_media=auxo_media, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="uptake")
excretion_phenoset = util.create_phenotypeset_from_compounds(
    metaboliteIDs, base_media=auxo_media, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="excretion")
agrowth_phenoset = util.create_phenotypeset_from_compounds(
    metaboliteIDs, base_media=anaerobicPyruvate, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="agrowth")
# growth_phenoset = util.create_phenotypeset_from_compounds(
#     metabolites, base_media=gmm_base_media, base_uptake=0, base_excretion=1000, global_atom_limits={}, type="growth")
phenotypes = {"uptake": uptake_phenoset, "excretion": excretion_phenoset, "agrowth": agrowth_phenoset}

python version 3.12.3

['/home/afreiburger/repos/cobrakbase',
 '/home/afreiburger/repos/KBBaseModules',
 '/home/afreiburger/repos/chenry_utility_module/lib',
 '/home/afreiburger/repos/cb_annotation_ontology_api/lib',
 '/home/afreiburger/repos/KB-ModelSEEDReconstruction/lib',
 '/home/afreiburger/repos/MergeMetabolicAnnotations/lib',
 '/home/afreiburger/repos/codiffusion_bioreactor',
 '/usr/lib/python312.zip',
 '/usr/lib/python3.12',
 '/usr/lib/python3.12/lib-dynload',
 '',
 '/home/afreiburger/repos/.venv/lib/python3.12/site-packages',
 '/home/afreiburger/repos/.venv/lib/python3.12/site-packages/libsbml',
 '/home/afreiburger/repos']

KBBaseModules 0.0.1
cobrakbase 0.3.1
Output files printed to:/home/afreiburger/repos/codiffusion_bioreactor/Sludge/nboutput when using KBDevUtils.output_dir

# create community models from the member models and abundances

In [1]:
from cobra.io import read_sbml_model, write_sbml_model
from pandas import read_csv, Series
from mscommunity import build_from_species_models
from tqdm import tqdm
from json import load
import os

iterativeIDs = load(open("model_inputs/iterativeIDs.json", 'r'))
ASV_sets = load(open("modeling_files/ASV_sets.json", 'r'))
redunant_asvs = {v:k for k,vs in ASV_sets.items() for v in vs}
abundances = load(open("modeling_files/ASVset_abundances.json", 'r'))
abundances = {sample: {iterativeIDs.get(ASV): abund for ASV, abund in content.items()}
              for sample, content in abundances.items()}
abundances_new = {sample: {iterativeIDs.get(ASV): {"abundance": abund} for ASV, abund in content.items()}
              for sample, content in abundances.items()}

def create_comm(item):
    sample, abundances = item
    models = []
    for ASVset, abun in abundances.items():
        # ASVset = iterativeIDs[redunant_asvs.get(ASV, ASV)]
        # print(ASVset)
        model_path = f"gapfilled_models/{ASVset}_gf.xml"
        #TODO:  investigate why these ASVs did not have any genomeIDs
        if not os.path.exists(model_path):  # some ASVs have no genomeIDs
            continue
            
        model = read_sbml_model(model_path)
        model.id = ASVset
        models.append(model)
    modelID = f"{sample}_comm"
    modelName = f"{sample}_comm"
    print(len(models))
    comm_model = build_from_species_models(models, modelID, modelName, printing=True) #abundances_new, printing=True)
    write_sbml_model(comm_model, f"comm_models/{modelID}.xml")

# parallelize the effort
args = [item for item in abundances.items() if not os.path.exists(f"comm_models/{item[0]}_comm.xml")]
print(len(args), "will be processed")
parallelize = False
if parallelize:
    from multiprocess import Pool
    from os import cpu_count
    
    cpus = min(len(args), int(cpu_count()/8))
    print(f"{cpus} cores are being used.  The first argument is {args[0]}")
    pool = Pool(cpus)
    outputs = pool.map(create_comm, args)
    
    print(f"missing iterativeIDs", missing_iterativeIDs)
    print(f"missing IDs", missing_IDs)
else:
    for arg in args:
        # print(arg)
        create_comm(arg)
        # break

modelseedpy 0.3.3

/home/afreiburger/repos/MSCommunity/mscommunity/commhelper.py:25: SyntaxWarning: invalid escape sequence '\_'
  return re.sub("(\_\w\d)", "", ID)
/home/afreiburger/repos/MSCommunity/mscommunity/commhelper.py:111: SyntaxWarning: invalid escape sequence '\d'
  if re.search('^(bio)(\d+)$', rxn.id) or "biomass" in rxn.id:

19 will be processed
156
156 models are being processed
1058 metabolites of midas_g_4042.3 are being processed
midas_g_4042.3 biomass metabolite captured cpd11416_c1
1048 reactions of midas_g_4042.3 are being processed
bio1 from midas_g_4042.3 becomes bio2
987 metabolites of midas_g_269.4 are being processed
midas_g_269.4 biomass metabolite captured cpd11416_c2
986 reactions of midas_g_269.4 are being processed
bio1 from midas_g_269.4 becomes bio3
941 metabolites of midas_g_52.2 are being processed
midas_g_52.2 biomass metabolite captured cpd11416_c3
950 reactions of midas_g_52.2 are being processed
bio1 from midas_g_52.2 becomes bio4
796 metabolites of OPB41.1 are being processed
OPB41.1 biomass metabolite captured cpd11416_c4
812 reactions of OPB41.1 are being processed
bio1 from OPB41.1 becomes bio5
787 metabolites of midas_g_531.1 are being processed
midas_g_531.1 biomass metabolite captured cpd11416_c5
784 reactions of midas_g_531.1 are being processed
bio1 from midas_g_531.1 becomes bio6
1073 metabolites of IMCC26207.3 are being processed
IMCC26207.3 biomass metabolite captured cpd11416_c6
1100 reactions of IMCC26207.3 are being processed
bio1 from IMCC26207.3 becomes bio7
1751 metabolites of Brooklawnia.1 are being processed
Brooklawnia.1 biomass metabolite captured cpd11416_c7
2139 reactions of Brooklawnia.1 are being processed
bio1 from Brooklawnia.1 becomes bio8
1751 metabolites of Propionicicella.4 are being processed
Propionicicella.4 biomass metabolite captured cpd11416_c8
2103 reactions of Propionicicella.4 are being processed
bio1 from Propionicicella.4 becomes bio9
1452 metabolites of Mycobacterium.6 are being processed
Mycobacterium.6 biomass metabolite captured cpd11416_c9
1654 reactions of Mycobacterium.6 are being processed
bio1 from Mycobacterium.6 becomes bio10
1547 metabolites of Mycobacterium.13 are being processed
Mycobacterium.13 biomass metabolite captured cpd11416_c10
1797 reactions of Mycobacterium.13 are being processed
bio1 from Mycobacterium.13 becomes bio11
1224 metabolites of Mycobacterium.14 are being processed
Mycobacterium.14 biomass metabolite captured cpd11416_c11
1375 reactions of Mycobacterium.14 are being processed
bio1 from Mycobacterium.14 becomes bio12
1157 metabolites of Gordonia.6 are being processed
Gordonia.6 biomass metabolite captured cpd11416_c12
1235 reactions of Gordonia.6 are being processed
bio1 from Gordonia.6 becomes bio13
1075 metabolites of Leucobacter.3 are being processed
Leucobacter.3 biomass metabolite captured cpd11416_c13
1160 reactions of Leucobacter.3 are being processed
bio1 from Leucobacter.3 becomes bio14
1065 metabolites of Microbacterium.10 are being processed
Microbacterium.10 biomass metabolite captured cpd11416_c14
1178 reactions of Microbacterium.10 are being processed
bio1 from Microbacterium.10 becomes bio15
985 metabolites of midas_g_399.2 are being processed
midas_g_399.2 biomass metabolite captured cpd11416_c15
1024 reactions of midas_g_399.2 are being processed
bio1 from midas_g_399.2 becomes bio16
884 metabolites of midas_g_399.4 are being processed
midas_g_399.4 biomass metabolite captured cpd11416_c16
914 reactions of midas_g_399.4 are being processed
bio1 from midas_g_399.4 becomes bio17
896 metabolites of midas_g_399.5 are being processed
midas_g_399.5 biomass metabolite captured cpd11416_c17
935 reactions of midas_g_399.5 are being processed
bio1 from midas_g_399.5 becomes bio18
853 metabolites of midas_g_497.1 are being processed
midas_g_497.1 biomass metabolite captured cpd11416_c18
874 reactions of midas_g_497.1 are being processed
bio1 from midas_g_497.1 becomes bio19
828 metabolites of Methanobacterium.6 are being processed
Methanobacterium.6 biomass metabolite captured cpd11416_c19
792 reactions of Methanobacterium.6 are being processed
bio1 from Methanobacterium.6 becomes bio20
749 metabolites of Methanobacteriaceae.1 are being processed
Methanobacteriaceae.1 biomass metabolite captured cpd11416_c20
732 reactions of Methanobacteriaceae.1 are being processed
bio1 from Methanobacteriaceae.1 becomes bio21
819 metabolites of Methanobacterium.5 are being processed
Methanobacterium.5 biomass metabolite captured cpd11416_c21
788 reactions of Methanobacterium.5 are being processed
bio1 from Methanobacterium.5 becomes bio22
723 metabolites of Methanobacterium.90 are being processed
Methanobacterium.90 biomass metabolite captured cpd11416_c22
712 reactions of Methanobacterium.90 are being processed
bio1 from Methanobacterium.90 becomes bio23
878 metabolites of midas_g_5426.1 are being processed
midas_g_5426.1 biomass metabolite captured cpd11416_c23
874 reactions of midas_g_5426.1 are being processed
bio1 from midas_g_5426.1 becomes bio24
1218 metabolites of Syner-01.1 are being processed
Syner-01.1 biomass metabolite captured cpd11416_c24
1316 reactions of Syner-01.1 are being processed
bio1 from Syner-01.1 becomes bio25
1249 metabolites of Syner-01.2 are being processed
Syner-01.2 biomass metabolite captured cpd11416_c25
1346 reactions of Syner-01.2 are being processed
bio1 from Syner-01.2 becomes bio26
1065 metabolites of Aminivibrio.1 are being processed
Aminivibrio.1 biomass metabolite captured cpd11416_c26
1111 reactions of Aminivibrio.1 are being processed
bio1 from Aminivibrio.1 becomes bio27
818 metabolites of Ca_Cloacimonas.2 are being processed
Ca_Cloacimonas.2 biomass metabolite captured cpd11416_c27
843 reactions of Ca_Cloacimonas.2 are being processed
bio1 from Ca_Cloacimonas.2 becomes bio28
988 metabolites of LNR_A2-18.1 are being processed
LNR_A2-18.1 biomass metabolite captured cpd11416_c28
985 reactions of LNR_A2-18.1 are being processed
bio1 from LNR_A2-18.1 becomes bio29
864 metabolites of Ca_Cloacimonas.4 are being processed
Ca_Cloacimonas.4 biomass metabolite captured cpd11416_c29
900 reactions of Ca_Cloacimonas.4 are being processed
bio1 from Ca_Cloacimonas.4 becomes bio30
1387 metabolites of midas_g_25828.1 are being processed
midas_g_25828.1 biomass metabolite captured cpd11416_c30
1675 reactions of midas_g_25828.1 are being processed
bio1 from midas_g_25828.1 becomes bio31
1159 metabolites of Marinilabiliaceae.1 are being processed
Marinilabiliaceae.1 biomass metabolite captured cpd11416_c31
1215 reactions of Marinilabiliaceae.1 are being processed
bio1 from Marinilabiliaceae.1 becomes bio32
1032 metabolites of midas_g_19.2 are being processed
midas_g_19.2 biomass metabolite captured cpd11416_c32
1080 reactions of midas_g_19.2 are being processed
bio1 from midas_g_19.2 becomes bio33
1440 metabolites of midas_g_36215.1 are being processed
midas_g_36215.1 biomass metabolite captured cpd11416_c33
1736 reactions of midas_g_36215.1 are being processed
bio1 from midas_g_36215.1 becomes bio34
876 metabolites of midas_g_36215.6 are being processed
midas_g_36215.6 biomass metabolite captured cpd11416_c34
862 reactions of midas_g_36215.6 are being processed
bio1 from midas_g_36215.6 becomes bio35
854 metabolites of DMER64.3 are being processed
DMER64.3 biomass metabolite captured cpd11416_c35
888 reactions of DMER64.3 are being processed
bio1 from DMER64.3 becomes bio36
1581 metabolites of Fermentimonas.6 are being processed
Fermentimonas.6 biomass metabolite captured cpd11416_c36
1878 reactions of Fermentimonas.6 are being processed
bio1 from Fermentimonas.6 becomes bio37
1077 metabolites of Proteiniphilum.1 are being processed
Proteiniphilum.1 biomass metabolite captured cpd11416_c37
1118 reactions of Proteiniphilum.1 are being processed
bio1 from Proteiniphilum.1 becomes bio38
1080 metabolites of Fermentimonas.1 are being processed
Fermentimonas.1 biomass metabolite captured cpd11416_c38
1113 reactions of Fermentimonas.1 are being processed
bio1 from Fermentimonas.1 becomes bio39
852 metabolites of Proteiniphilum.22 are being processed
Proteiniphilum.22 biomass metabolite captured cpd11416_c39
901 reactions of Proteiniphilum.22 are being processed
bio1 from Proteiniphilum.22 becomes bio40
570 metabolites of midas_g_9269.1 are being processed
midas_g_9269.1 biomass metabolite captured cpd11416_c40
599 reactions of midas_g_9269.1 are being processed
bio1 from midas_g_9269.1 becomes bio41
1050 metabolites of midas_g_83754.1 are being processed
midas_g_83754.1 biomass metabolite captured cpd11416_c41
1073 reactions of midas_g_83754.1 are being processed
bio1 from midas_g_83754.1 becomes bio42
1485 metabolites of Thermovirga.2 are being processed
Thermovirga.2 biomass metabolite captured cpd11416_c42
1772 reactions of Thermovirga.2 are being processed
bio1 from Thermovirga.2 becomes bio43
1026 metabolites of Bacteria.21 are being processed
Bacteria.21 biomass metabolite captured cpd11416_c43
1029 reactions of Bacteria.21 are being processed
bio1 from Bacteria.21 becomes bio44
986 metabolites of Thiopseudomonas.1 are being processed
Thiopseudomonas.1 biomass metabolite captured cpd11416_c44
1023 reactions of Thiopseudomonas.1 are being processed
bio1 from Thiopseudomonas.1 becomes bio45
1116 metabolites of Pseudomonas.5 are being processed
Pseudomonas.5 biomass metabolite captured cpd11416_c45
1174 reactions of Pseudomonas.5 are being processed
bio1 from Pseudomonas.5 becomes bio46
1156 metabolites of Pseudomonas.7 are being processed
Pseudomonas.7 biomass metabolite captured cpd11416_c46
1203 reactions of Pseudomonas.7 are being processed
bio1 from Pseudomonas.7 becomes bio47
1399 metabolites of Rhodanobacter.5 are being processed
Rhodanobacter.5 biomass metabolite captured cpd11416_c47
1627 reactions of Rhodanobacter.5 are being processed
bio1 from Rhodanobacter.5 becomes bio48
1349 metabolites of Rhodanobacter.2 are being processed
Rhodanobacter.2 biomass metabolite captured cpd11416_c48
1482 reactions of Rhodanobacter.2 are being processed
bio1 from Rhodanobacter.2 becomes bio49
1101 metabolites of Rheinheimera.1 are being processed
Rheinheimera.1 biomass metabolite captured cpd11416_c49
1193 reactions of Rheinheimera.1 are being processed
bio1 from Rheinheimera.1 becomes bio50
1067 metabolites of midas_g_70.1 are being processed
midas_g_70.1 biomass metabolite captured cpd11416_c50
1086 reactions of midas_g_70.1 are being processed
bio1 from midas_g_70.1 becomes bio51
1346 metabolites of Alcaligenaceae.6 are being processed
Alcaligenaceae.6 biomass metabolite captured cpd11416_c51
1459 reactions of Alcaligenaceae.6 are being processed
bio1 from Alcaligenaceae.6 becomes bio52
1050 metabolites of Pusillimonas.2 are being processed
Pusillimonas.2 biomass metabolite captured cpd11416_c52
1078 reactions of Pusillimonas.2 are being processed
bio1 from Pusillimonas.2 becomes bio53
1295 metabolites of Comamonas.3 are being processed
Comamonas.3 biomass metabolite captured cpd11416_c53
1538 reactions of Comamonas.3 are being processed
bio1 from Comamonas.3 becomes bio54
1153 metabolites of Rhodocyclaceae.5 are being processed
Rhodocyclaceae.5 biomass metabolite captured cpd11416_c54
1209 reactions of Rhodocyclaceae.5 are being processed
bio1 from Rhodocyclaceae.5 becomes bio55
1618 metabolites of Azoarcus.4 are being processed
Azoarcus.4 biomass metabolite captured cpd11416_c55
1940 reactions of Azoarcus.4 are being processed
bio1 from Azoarcus.4 becomes bio56
1438 metabolites of Thauera.2 are being processed
Thauera.2 biomass metabolite captured cpd11416_c56
1613 reactions of Thauera.2 are being processed
bio1 from Thauera.2 becomes bio57
987 metabolites of Desulfococcaceae.1 are being processed
Desulfococcaceae.1 biomass metabolite captured cpd11416_c57
993 reactions of Desulfococcaceae.1 are being processed
bio1 from Desulfococcaceae.1 becomes bio58
1137 metabolites of Desulfovibrio.3 are being processed
Desulfovibrio.3 biomass metabolite captured cpd11416_c58
1190 reactions of Desulfovibrio.3 are being processed
bio1 from Desulfovibrio.3 becomes bio59
1040 metabolites of Desulfomicrobium.1 are being processed
Desulfomicrobium.1 biomass metabolite captured cpd11416_c59
1058 reactions of Desulfomicrobium.1 are being processed
bio1 from Desulfomicrobium.1 becomes bio60
1279 metabolites of Desulfovibrionaceae.2 are being processed
Desulfovibrionaceae.2 biomass metabolite captured cpd11416_c60
1422 reactions of Desulfovibrionaceae.2 are being processed
bio1 from Desulfovibrionaceae.2 becomes bio61
1097 metabolites of Parvibaculum.1 are being processed
Parvibaculum.1 biomass metabolite captured cpd11416_c61
1085 reactions of Parvibaculum.1 are being processed
bio1 from Parvibaculum.1 becomes bio62
1310 metabolites of Amaricoccus.1 are being processed
Amaricoccus.1 biomass metabolite captured cpd11416_c62
1388 reactions of Amaricoccus.1 are being processed
bio1 from Amaricoccus.1 becomes bio63
1386 metabolites of Amaricoccus.3 are being processed
Amaricoccus.3 biomass metabolite captured cpd11416_c63
1515 reactions of Amaricoccus.3 are being processed
bio1 from Amaricoccus.3 becomes bio64
1653 metabolites of Rhodobacter.5 are being processed
Rhodobacter.5 biomass metabolite captured cpd11416_c64
1987 reactions of Rhodobacter.5 are being processed
bio1 from Rhodobacter.5 becomes bio65
1086 metabolites of Caulobacteraceae.1 are being processed
Caulobacteraceae.1 biomass metabolite captured cpd11416_c65
1159 reactions of Caulobacteraceae.1 are being processed
bio1 from Caulobacteraceae.1 becomes bio66
1124 metabolites of Hyphomonas.1 are being processed
Hyphomonas.1 biomass metabolite captured cpd11416_c66
1157 reactions of Hyphomonas.1 are being processed
bio1 from Hyphomonas.1 becomes bio67
1137 metabolites of Rhizobiaceae.1 are being processed
Rhizobiaceae.1 biomass metabolite captured cpd11416_c67
1178 reactions of Rhizobiaceae.1 are being processed
bio1 from Rhizobiaceae.1 becomes bio68
1429 metabolites of Aquamicrobium.1 are being processed
Aquamicrobium.1 biomass metabolite captured cpd11416_c68
1556 reactions of Aquamicrobium.1 are being processed
bio1 from Aquamicrobium.1 becomes bio69
1346 metabolites of Aquamicrobium.5 are being processed
Aquamicrobium.5 biomass metabolite captured cpd11416_c69
1419 reactions of Aquamicrobium.5 are being processed
bio1 from Aquamicrobium.5 becomes bio70
1247 metabolites of Aquamicrobium.7 are being processed
Aquamicrobium.7 biomass metabolite captured cpd11416_c70
1296 reactions of Aquamicrobium.7 are being processed
bio1 from Aquamicrobium.7 becomes bio71
1306 metabolites of Devosia.1 are being processed
Devosia.1 biomass metabolite captured cpd11416_c71
1442 reactions of Devosia.1 are being processed
bio1 from Devosia.1 becomes bio72
1127 metabolites of Devosia.7 are being processed
Devosia.7 biomass metabolite captured cpd11416_c72
1221 reactions of Devosia.7 are being processed
bio1 from Devosia.7 becomes bio73
1452 metabolites of Stappia.1 are being processed
Stappia.1 biomass metabolite captured cpd11416_c73
1625 reactions of Stappia.1 are being processed
bio1 from Stappia.1 becomes bio74
1156 metabolites of Hyphomicrobium.2 are being processed
Hyphomicrobium.2 biomass metabolite captured cpd11416_c74
1189 reactions of Hyphomicrobium.2 are being processed
bio1 from Hyphomicrobium.2 becomes bio75
1324 metabolites of Hyphomicrobium.10 are being processed
Hyphomicrobium.10 biomass metabolite captured cpd11416_c75
1415 reactions of Hyphomicrobium.10 are being processed
bio1 from Hyphomicrobium.10 becomes bio76
1104 metabolites of Rhodobacteraceae.6 are being processed
Rhodobacteraceae.6 biomass metabolite captured cpd11416_c76
1118 reactions of Rhodobacteraceae.6 are being processed
bio1 from Rhodobacteraceae.6 becomes bio77
514 metabolites of midas_g_57.2 are being processed
midas_g_57.2 biomass metabolite captured cpd11416_c77
561 reactions of midas_g_57.2 are being processed
bio1 from midas_g_57.2 becomes bio78
1189 metabolites of Xanthobacteraceae.1 are being processed
Xanthobacteraceae.1 biomass metabolite captured cpd11416_c78
1244 reactions of Xanthobacteraceae.1 are being processed
bio1 from Xanthobacteraceae.1 becomes bio79
1082 metabolites of Pseudochelatococcus.1 are being processed
Pseudochelatococcus.1 biomass metabolite captured cpd11416_c79
1142 reactions of Pseudochelatococcus.1 are being processed
bio1 from Pseudochelatococcus.1 becomes bio80
1331 metabolites of Afipia.1 are being processed
Afipia.1 biomass metabolite captured cpd11416_c80
1416 reactions of Afipia.1 are being processed
bio1 from Afipia.1 becomes bio81
1204 metabolites of Alphaproteobacteria.4 are being processed
Alphaproteobacteria.4 biomass metabolite captured cpd11416_c81
1220 reactions of Alphaproteobacteria.4 are being processed
bio1 from Alphaproteobacteria.4 becomes bio82
906 metabolites of Smithella.2 are being processed
Smithella.2 biomass metabolite captured cpd11416_c82
893 reactions of Smithella.2 are being processed
bio1 from Smithella.2 becomes bio83
1214 metabolites of Syntrophobacter.1 are being processed
Syntrophobacter.1 biomass metabolite captured cpd11416_c83
1270 reactions of Syntrophobacter.1 are being processed
bio1 from Syntrophobacter.1 becomes bio84
1083 metabolites of Syntrophobacter.7 are being processed
Syntrophobacter.7 biomass metabolite captured cpd11416_c84
1093 reactions of Syntrophobacter.7 are being processed
bio1 from Syntrophobacter.7 becomes bio85
998 metabolites of Desulfuromonadaceae.1 are being processed
Desulfuromonadaceae.1 biomass metabolite captured cpd11416_c85
994 reactions of Desulfuromonadaceae.1 are being processed
bio1 from Desulfuromonadaceae.1 becomes bio86
826 metabolites of RBG-16-49-21.1 are being processed
RBG-16-49-21.1 biomass metabolite captured cpd11416_c86
808 reactions of RBG-16-49-21.1 are being processed
bio1 from RBG-16-49-21.1 becomes bio87
818 metabolites of midas_g_1408.1 are being processed
midas_g_1408.1 biomass metabolite captured cpd11416_c87
842 reactions of midas_g_1408.1 are being processed
bio1 from midas_g_1408.1 becomes bio88
1407 metabolites of Hydrogenedensaceae.1 are being processed
Hydrogenedensaceae.1 biomass metabolite captured cpd11416_c88
1567 reactions of Hydrogenedensaceae.1 are being processed
bio1 from Hydrogenedensaceae.1 becomes bio89
1059 metabolites of Pir4_lineage.7 are being processed
Pir4_lineage.7 biomass metabolite captured cpd11416_c89
1059 reactions of Pir4_lineage.7 are being processed
bio1 from Pir4_lineage.7 becomes bio90
1269 metabolites of midas_g_5834.2 are being processed
midas_g_5834.2 biomass metabolite captured cpd11416_c90
1362 reactions of midas_g_5834.2 are being processed
bio1 from midas_g_5834.2 becomes bio91
710 metabolites of Leptolinea.3 are being processed
Leptolinea.3 biomass metabolite captured cpd11416_c91
774 reactions of Leptolinea.3 are being processed
bio1 from Leptolinea.3 becomes bio92
987 metabolites of midas_g_156.1 are being processed
midas_g_156.1 biomass metabolite captured cpd11416_c92
1053 reactions of midas_g_156.1 are being processed
bio1 from midas_g_156.1 becomes bio93
1010 metabolites of Ca_Caldatribacterium.1 are being processed
Ca_Caldatribacterium.1 biomass metabolite captured cpd11416_c93
1082 reactions of Ca_Caldatribacterium.1 are being processed
bio1 from Ca_Caldatribacterium.1 becomes bio94
1253 metabolites of midas_g_3409.1 are being processed
midas_g_3409.1 biomass metabolite captured cpd11416_c94
1335 reactions of midas_g_3409.1 are being processed
bio1 from midas_g_3409.1 becomes bio95
897 metabolites of midas_g_249.4 are being processed
midas_g_249.4 biomass metabolite captured cpd11416_c95
902 reactions of midas_g_249.4 are being processed
bio1 from midas_g_249.4 becomes bio96
897 metabolites of Thermovirga.6 are being processed
Thermovirga.6 biomass metabolite captured cpd11416_c96
935 reactions of Thermovirga.6 are being processed
bio1 from Thermovirga.6 becomes bio97
1024 metabolites of midas_g_515.1 are being processed
midas_g_515.1 biomass metabolite captured cpd11416_c97
1051 reactions of midas_g_515.1 are being processed
bio1 from midas_g_515.1 becomes bio98
790 metabolites of midas_g_4306.1 are being processed
midas_g_4306.1 biomass metabolite captured cpd11416_c98
850 reactions of midas_g_4306.1 are being processed

In [15]:
from json import load
abundances = load(open("modeling_files/ASVset_abundances.json", 'r'))
list(list(abundances.values())[0].values())[0]

0.0035438998239284624

## Test that the models are operational

In [1]:
from cobra.io import read_sbml_model
from glob import glob

# for path in glob("models/F34_comm.xml"):
# for path in glob("comm_models/G12_comm.xml"):
    # print(path.split("/")[-1])
model = read_sbml_model("comm_models/P12_comm.xml")
# break

In [2]:
print(model.objective)
display(model.summary())

Maximize
1.0*bio1 - 1.0*bio1_reverse_b18f7

In [3]:
model.reactions.bio1.reaction

'0.0277777777777778 cpd11416_c1 + 0.0277777777777778 cpd11416_c10 + 0.0277777777777778 cpd11416_c11 + 0.0277777777777778 cpd11416_c12 + 0.0277777777777778 cpd11416_c13 + 0.0277777777777778 cpd11416_c14 + 0.0277777777777778 cpd11416_c15 + 0.0277777777777778 cpd11416_c16 + 0.0277777777777778 cpd11416_c17 + 0.0277777777777778 cpd11416_c18 + 0.0277777777777778 cpd11416_c19 + 0.0277777777777778 cpd11416_c2 + 0.0277777777777778 cpd11416_c20 + 0.0277777777777778 cpd11416_c21 + 0.0277777777777778 cpd11416_c22 + 0.0277777777777778 cpd11416_c23 + 0.0277777777777778 cpd11416_c24 + 0.0277777777777778 cpd11416_c25 + 0.0277777777777778 cpd11416_c26 + 0.0277777777777778 cpd11416_c27 + 0.0277777777777778 cpd11416_c28 + 0.0277777777777778 cpd11416_c29 + 0.0277777777777778 cpd11416_c3 + 0.0277777777777778 cpd11416_c30 + 0.0277777777777778 cpd11416_c31 + 0.0277777777777778 cpd11416_c32 + 0.0277777777777778 cpd11416_c33 + 0.0277777777777778 cpd11416_c34 + 0.0277777777777778 cpd11416_c35 + 0.0277777777777778 cpd11416_c36 + 0.0277777777777778 cpd11416_c4 + 0.0277777777777778 cpd11416_c5 + 0.0277777777777778 cpd11416_c6 + 0.0277777777777778 cpd11416_c7 + 0.0277777777777778 cpd11416_c8 + 0.0277777777777778 cpd11416_c9 --> cpd11416_c0'

In [4]:
bioReactions = []
for rxn in model.reactions:
    if "bio" in rxn.id:
        bioReactions.append(rxn.id)
bioReactions = sorted(bioReactions)
print(len(bioReactions), bioReactions)

37 ['bio1', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14', 'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio20', 'bio21', 'bio22', 'bio23', 'bio24', 'bio25', 'bio26', 'bio27', 'bio28', 'bio29', 'bio3', 'bio30', 'bio31', 'bio32', 'bio33', 'bio34', 'bio35', 'bio36', 'bio37', 'bio4', 'bio5', 'bio6', 'bio7', 'bio8', 'bio9']

In [5]:
bioCompounds = []
for cpd in model.metabolites:
    if "cpd11416" in cpd.id:
        bioCompounds.append(cpd.id)
bioCompounds = sorted(bioCompounds)
print(len(bioCompounds), bioCompounds)

37 ['cpd11416_c0', 'cpd11416_c1', 'cpd11416_c10', 'cpd11416_c11', 'cpd11416_c12', 'cpd11416_c13', 'cpd11416_c14', 'cpd11416_c15', 'cpd11416_c16', 'cpd11416_c17', 'cpd11416_c18', 'cpd11416_c19', 'cpd11416_c2', 'cpd11416_c20', 'cpd11416_c21', 'cpd11416_c22', 'cpd11416_c23', 'cpd11416_c24', 'cpd11416_c25', 'cpd11416_c26', 'cpd11416_c27', 'cpd11416_c28', 'cpd11416_c29', 'cpd11416_c3', 'cpd11416_c30', 'cpd11416_c31', 'cpd11416_c32', 'cpd11416_c33', 'cpd11416_c34', 'cpd11416_c35', 'cpd11416_c36', 'cpd11416_c4', 'cpd11416_c5', 'cpd11416_c6', 'cpd11416_c7', 'cpd11416_c8', 'cpd11416_c9']

# Community modeling

## Load the community models

In [ ]:
from cobra.io import read_sbml_model
from tqdm import tqdm
from glob import glob

models = {}
num_models = 2
for model_path in tqdm(glob("comm_models/*.xml")[:num_models]):
    modelID = model_path.split("/")[-1].replace(".xml", '')
    print("loading", modelID)
    model = read_sbml_model(model_path)
    model.id = modelID
    models[modelID] = model

  0%|          | 0/2 [00:00<?, ?it/s]'' is not a valid SBML 'SId'.

loading 10AB_comm

## Constraints

### Process data

#### convert measurements into MSIDs

In [ ]:
from collections import Counter
from pandas import read_csv, set_option
from json import dump

set_option("display.max_columns", None)

mapping = {"Media Acetate (mol/L)": "cpd00029_in", "Media Propionate (mol/L)": "cpd00141_in",
           "Media Butyrate (mol/L)": "cpd00211_in", "Waste Effluent Acetate (mol/L)": "cpd00029_out",
           "Waste Effluent Propionate (mol/L)": "cpd00141_out", "Waste Effluent Butyrate (mol/L)": "cpd00211_out",
           "Approximate Total Influent C (mol/min) based on Media recipe": "media_carbon_in",
           "Media Total COD (mg/L) Hach": "media_cpd00007",
           "Measured Total Influent C (mol/min)": "carbon_in",
           "Gas Composition (% CH4)": "%cpd01024", "Gas Composition (% H2)": "%cpd11640", "Gas Composition (% CO2)": "%cpd00011",
           "CH4 breakthrough (mol/min)": "cpd01024_out", "H2 breakthrough (mol/min)": "cpd11640_out", "CO2 breakthrough (mol/min)": "cpd00011_out",
           "Accounted C (%) based on MT sensors": "accounted_C"}


data = read_csv("model_inputs/measurements/Summary_interpolated.csv")
data["Media Total COD (mg/L) Hach"] /= 32000
data["carbon_out"] = data["Waste Effluent Dissolved Inorganic Carbon (mol C/L)"] + data["Waste Effluent Dissolved Organic Carbon (mol C/L)"
                        ] + data["Effluent C as measured (mol/min)"]
data.rename(columns=mapping, inplace=True)
data = data[data["Biomass Sample ID"].notna()].set_index("Biomass Sample ID")
# print(Counter(data.columns))
data_df = data.T.to_dict()
dump(data_df, open("model_inputs/measurements/Summer_interpolated_MSDB.json", 'w'), indent=2)
data

In [ ]:
data_df

### loading the media

In [ ]:
# import os
# # os.environ["HOME"] = "~/repos/cobrakbase"
# import cobrakbase

# with open("/home/afreiburger/.kbase/token", 'r') as token:
#     kbase_obj = cobrakbase.KBaseAPI(token.readline())

# media_ws = 207617
# media = kbase_obj.get_from_ws("Wolfe",207617)
2
# from modelseedpy.core.fbahelper import FBAHelper
# from json import dump
# media_js = FBAHelper.convert_kbase_media(media)

# dump(media_js, open("model_inputs/Wolfe.json", 'w'), indent=2)

from json import load
media = load(open("model_inputs/Wolfe.json", 'r'))

###

### Adding the media and element constraints

In [ ]:
from mscommunity import MSCommunity
from tqdm import tqdm

for ID, model in tqdm(models.items()):
    sample = ID.split("_")[0]
    models[ID] = MSCommunity(model, climit=data_df[sample]["carbon_in"]*1000, o2limit=data_df[sample]["media_cpd00007"]*1000)
    models[ID].util.add_medium = media

## Objective